// Utils
export const SHOW_BACKDROP = "SHOW_BACKDROP";
export const SET_BACKDROP_TYPE = "SET_BACKDROP_TYPE";
export const HIDE_BACKDROP = "HIDE_BACKDROP";
export const SHOW_MENU_BAR = "SHOW_MENU_BAR";
export const HIDE_MENU_BAR = "HIDE_MENU_BAR";
export const SHOW_SIDE_DRAWER = "SHOW_SIDE_DRAWER";
export const HIDE_SIDE_DRAWER = "HIDE_SIDE_DRAWER";
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

// Auth
export const SET_LOADING_AUTH = "SET_LOADING_AUTH";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT = "LOGOUT";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const SET_FETCH = "SET_FETCH";
export const UNSET_FETCH = "UNSET_FETCH";

// Profile
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const SET_LOADING_PROFILE = "SET_LOADING_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const SET_CURRENT_PROFILE = "SET_CURRENT_PROFILE";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_FOLLOWERS = "GET_FOLLOWERS";
export const GET_FOLLOWINGS = "GET_FOLLOWINGS";
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";
export const DELETE_EDUCATION = "DELETE_EDUCATION";
