// Utils
export const SHOW_BACKDROP = "SHOW_BACKDROP";
export const SET_BACKDROP_TYPE = "SET_BACKDROP_TYPE";
export const HIDE_BACKDROP = "HIDE_BACKDROP";
export const SHOW_MENU_BAR = "SHOW_MENU_BAR";
export const HIDE_MENU_BAR = "HIDE_MENU_BAR";
export const SHOW_SIDE_DRAWER = "SHOW_SIDE_DRAWER";
export const HIDE_SIDE_DRAWER = "HIDE_SIDE_DRAWER";
export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
export const CLOSE_COMPONENT = "CLOSE_COMPONENT";
export const SHOW_COMPONENT = "SHOW_COMPONENT";

// Auth
export const SET_LOADING_AUTH = "SET_LOADING_AUTH";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADED = "USER_LOADED";
export const LOGOUT = "LOGOUT";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const SET_FETCH = "SET_FETCH";
export const UNSET_FETCH = "UNSET_FETCH";

// Profile
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const SET_LOADING_PROFILE = "SET_LOADING_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const SET_CURRENT_PROFILE = "SET_CURRENT_PROFILE";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const GET_FOLLOWERS = "GET_FOLLOWERS";
export const GET_FOLLOWINGS = "GET_FOLLOWINGS";
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";
export const DELETE_EDUCATION = "DELETE_EDUCATION";
export const SET_PROGRESS = "SET_PROGRESS";
export const UNSET_PROGRESS = "UNSET_PROGRESS";
export const GITHUB_REPOS = "GITHUB_REPOS";
export const GITHUB_ERROR = "GITHUB_ERROR";

// Posts
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_SINGLE_POST = "GET_SINGLE_POST";
export const ADD_POST = "ADD_POST";
export const UPDATE_POST = "UPDATE_POST";
export const POST_ERROR = "POST_ERROR";
export const DELETE_POST = "DELETE_POST";
export const GET_LIKE_CREDENTIAL = "GET_LIKE_CREDENTIAL";
export const GET_MY_POSTS = "GET_MY_POSTS";
export const CLEAR_LIKES = "CLEAR_LIKES";
export const CLEAR_POSTS = "CLEAR_POSTS";
export const LIKE_A_POST = "LIKE_A_POST";
